export const ORDER_STATES = {
  OPEN: "OPEN",
  ASSIGNED: "ASSIGNED",
  IN_PROGRESS: "IN_PROGRESS",
  COMPLETED: "COMPLETED",
  CLOSED: "CLOSED",
  CANCELLED: "CANCELLED",
  DISPUTED: "DISPUTED",
  REFUND_PENDING: "REFUND_PENDING",
  REFUNDED: "REFUNDED",
  EVIDENCE_REJECTED: "EVIDENCE_REJECTED",
};

export const ORDER_ACTIONS = {
  CREATE: "CREATE",
  ASSIGN: "ASSIGN",
  CHECKIN: "CHECKIN",
  COMPLETE: "COMPLETE",
  CLOSE: "CLOSE",
  CANCEL: "CANCEL",
  DISPUTE: "DISPUTE",
  EVIDENCE_DECISION: "EVIDENCE_DECISION",
  REJECT_EVIDENCE: "REJECT_EVIDENCE",
};

const transitionTable = {
  [ORDER_STATES.OPEN]: {
    [ORDER_ACTIONS.ASSIGN]: ORDER_STATES.ASSIGNED,
    [ORDER_ACTIONS.CANCEL]: ORDER_STATES.CANCELLED,
  },
  [ORDER_STATES.ASSIGNED]: {
    [ORDER_ACTIONS.CHECKIN]: ORDER_STATES.IN_PROGRESS,
    [ORDER_ACTIONS.CANCEL]: ORDER_STATES.CANCELLED,
  },
  [ORDER_STATES.IN_PROGRESS]: {
    [ORDER_ACTIONS.COMPLETE]: ORDER_STATES.COMPLETED,
    [ORDER_ACTIONS.CANCEL]: ORDER_STATES.CANCELLED,
    [ORDER_ACTIONS.DISPUTE]: ORDER_STATES.DISPUTED,
  },
  [ORDER_STATES.COMPLETED]: {
    [ORDER_ACTIONS.CLOSE]: ORDER_STATES.CLOSED,
    [ORDER_ACTIONS.DISPUTE]: ORDER_STATES.DISPUTED,
    [ORDER_ACTIONS.EVIDENCE_DECISION]: ORDER_STATES.CLOSED,
    [ORDER_ACTIONS.REJECT_EVIDENCE]: ORDER_STATES.EVIDENCE_REJECTED,
  },
  [ORDER_STATES.EVIDENCE_REJECTED]: {
    [ORDER_ACTIONS.COMPLETE]: ORDER_STATES.COMPLETED,
    [ORDER_ACTIONS.EVIDENCE_DECISION]: ORDER_STATES.CLOSED,
    [ORDER_ACTIONS.REJECT_EVIDENCE]: ORDER_STATES.EVIDENCE_REJECTED,
  },
  [ORDER_STATES.DISPUTED]: {
    [ORDER_ACTIONS.CLOSE]: ORDER_STATES.CLOSED,
  },
};

export function nextOrderState(current, action) {
  const allowed = transitionTable[current];
  if (!allowed || !allowed[action]) {
    throw new Error(`Transisi tidak valid dari ${current} menggunakan aksi ${action}`);
  }
  return allowed[action];
}

export function getTransitionTable() {
  return transitionTable;
}
